name: Backend CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ci"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: node
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
   #Steup node
   #- uses: actions/setup-node@v1
   #with:
   #node-version: '12.x'
       
   #Install dependencies
    - name: Install and Test
      run: 
        npm install
        npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.Docker_User }} -p ${{ secrets.Docker_Password }}
   
   #Build Docker Image
     
      - name: Build
        run: docker build -t back
        
      - name: Tags
        run:
          docker tag back ${{ secrets.Docker_User }}/back:${{ github.sha }}
          docker tag back ${{ secrets.Docker_User }}/back:latest
     
     # Push Docker Images
      - name: Push
        run:
          docker push ${{ secrets.Docker_User }}/back:${{ github.sha }}
          docker push ${{ secrets.Docker_User }}/back:latest
        
